project:
  type: website

website:
  title: "Mundo Marinho"
  navbar:
    left:
      - text: Início
        href: index.qmd
      - text: Sobre
        href: about.qmd
      - text: Blog
        href: posts/
      #- text: Projetos
        #href: projects.qmd
  page-footer:
    left: "© 2025 Vitor Marinho"
    right:
      - icon: github
        href: https://github.com/vitormarinh0
      - icon: linkedin
        href: https://www.linkedin.com/in/vitor-marinho-a4b742242

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">