project:
  type: website

website:
  title: "Data-viz por Vitor Marinho"
  navbar:
    left:
      - text: Início
        file: index.qmd
      - text: Publicações
        file: posts/index.qmd
      - text: Sobre
        file: about.qmd

format:
  lumo-html:
    title: "Vitor Marinho"
    self-contained: true
    primary-color: "#69b3a2"
    is-particlejs-enabled: true
    bg-image: 

extensions:
  - holtzy/lumo